name: VideoExtractionServer
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - numpy=1.19.5
  - pillow=8.3.0
  - tensorflow-gpu=2.5.0
  - opencv-python=4.5.2.54
  - ray=1.6.0
  - torch=1.9.0
  - torchvision=0.10.0
  - pandas
  - matplotlib
  - tqdm
  - seaborn